export const START_REQUEST = 'START_REQUEST';
export const FINISH_REQUEST = 'FINISH_REQUEST';
export const CAPTCHA_VERIFIED = 'CAPTCHA_VERIFIED';
export const LOGIN_SUCCESSFULLY = 'LOGIN_SUCCESSFULLY';
export const USERINFO_READY = 'USERINFO_READY';
export const REFRESH_CAPTACHA = 'REFRESH_CAPTACHA';
export const TOGGLE_LANGUAGE = 'TOGGLE_LANGUAGE';
